version: '3'
services:
  httpd:
    build: .
    environment:
      - DOMAINS
      - WEBMASTER_MAIL
      - WEBSERVER_HOSTNAME
      - STAGING
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "config:/etc/apache2"
      - "letsencrypt:/etc/letsencrypt"
      - "log:/var/log/apache2"

volumes:
  config:
  letsencrypt:
  log: